export const WHATSAPP_BROADCAST_MIN_DELAY_SECONDS = Number(process.env.WHATSAPP_BROADCAST_MIN_DELAY_SECONDS ?? 60);
export const WHATSAPP_BROADCAST_MAX_DELAY_SECONDS = Number(process.env.WHATSAPP_BROADCAST_MAX_DELAY_SECONDS ?? 140);
export const WHATSAPP_BROADCAST_MAX_BATCH_SIZE = Number(process.env.WHATSAPP_BROADCAST_MAX_BATCH_SIZE ?? 205);
export const WHATSAPP_BROADCAST_MAX_PER_HOUR = Number(process.env.WHATSAPP_BROADCAST_MAX_PER_HOUR ?? 35);
export const WHATSAPP_BROADCAST_AUTO_PAUSE_FAILURES = Number(process.env.WHATSAPP_BROADCAST_AUTO_PAUSE_FAILURES ?? 5);
