export const WHATSAPP_BROADCAST_MIN_DELAY_SECONDS = Number(process.env.WHATSAPP_BROADCAST_MIN_DELAY_SECONDS ?? 5);
export const WHATSAPP_BROADCAST_MAX_DELAY_SECONDS = Number(process.env.WHATSAPP_BROADCAST_MAX_DELAY_SECONDS ?? 10);
export const WHATSAPP_BROADCAST_MAX_BATCH_SIZE = Number(process.env.WHATSAPP_BROADCAST_MAX_BATCH_SIZE ?? 40);
export const WHATSAPP_BROADCAST_MAX_PER_HOUR = Number(process.env.WHATSAPP_BROADCAST_MAX_PER_HOUR ?? 60);
export const WHATSAPP_BROADCAST_AUTO_PAUSE_FAILURES = Number(process.env.WHATSAPP_BROADCAST_AUTO_PAUSE_FAILURES ?? 5);
